image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev

stages:
    - qa-vps
    - staging-heroku
    - production-heroku

staging-heroku:
    stage: staging-heroku
    image: ruby:latest
    script:
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    when: manual

production-heroku:
    stage: production-heroku
    image: ruby:latest
    script:
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    when: manual

qa-vps:
    stage: qa-vps
    image: node:latest
    script:
        - export APP_VERSION="`cat "version.txt"`"
        - export LOCAL_PRIVATE_KEY_PATH="./id_rsa_${VPS_USER}_${VPS_NAME}"
        - echo $VPS_PRIVATE_KEY_FILE > $LOCAL_PRIVATE_KEY_PATH
        - chmod 600 $LOCAL_PRIVATE_KEY_PATH
        - sh scripts/docker_build.sh $APP_VERSION
        - sh scripts/docker_push.sh $DOCKER_ACCOUNT $DOCKER_PASSWORD $APP_VERSION
        - sh scripts/vps/deploy_to_vps.sh $APP_VERSION $VPS_USER $VPS_NAME $VPS_PORT $LOCAL_PRIVATE_KEY_PATH
    when: manual
