# File: docker-compose.yml para fynapp_frontend (alone)
# Para poder hacer pruebas del build mas rapidamente, sin tener ejecutar `docker build` que tarda mas en decirme si hay problemas con el npm install...
version: "3"

services:
  fynapp_frontend:
    container_name: fynapp_frontend
    # image: mediabros/fynapp_frontend:v0.1.1-amd64
    build: .
    platform: linux/x86_64
    ports:
      - 3001:3001
    expose:
      - 3001
    environment:
      - REACT_APP_API_URL=http://fynapp_backend:5000
